### ISSUE TITLE
DbOpenHelper leaks context in memory

### ISSUE THREAD

**Issue by spirosoik** [yigit/android-priority-jobqueue#121]
You can use a `WeakReference` of context to avoid leaking the context in the memory. You can detect it with leakcanary.

**Comment by yigit** [comment]
seems like you are constructing job manager with an activity context instead of the Application context.
It actually keeps a reference to the app context automatically but seems like still passing the given context to the sqlite queue.

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/JobManager.java#L92

You can easily fix it by passing the app context to the job manager.

In V2, this is already taken care of:

https://github.com/yigit/android-priority-jobqueue/blob/v2/jobqueue/src/main/java/com/birbit/android/jobqueue/config/Configuration.java#L119

**Comment by spirosoik** [comment]
@yigit thanks for the great explanation I'll try and I'll get back to you.

**Comment by yigit** [comment]
i've just released v2 alpha so closing this.
