### ISSUE TITLE
on refactoring my project

### ISSUE THREAD

**Issue by hubcin** [yigit/android-priority-jobqueue#142]
I have an instant messenger app and I want to implement job-queue to make every network request and other heavy tasks run in background.
1. I have to upload local image( compress and upload via HTTP) to the server first, and after I get the URL of that image, I'll make an HTTP request  and publish this image's URL.
The uploading process, or the HTTP request may all fail due to some error, how do I make this process( upload image and send the URL via HTTP)  as a Job since all the work that done in onRun() method should be synchronous?
2. I start a job without network. and in my client App I switch the user.  Because the LoginJob's priority is higher than any other jobs, so after the network recovered, new user logged in, other jobs that persisted on disk will run eventually, that make the newly logged user to publish the last user's post. how should I manage this kind of situation? Should I cancel all those job? But what happens when the last user come back to find that his/her new post is gone? 

I have so many doubts that makes me so hard to make decision on using priority-job-queue. 
The only thing I like in this library is the concept of running background task with a nice UX.

So I truly hope there would be any project example that demonstrate the usage of library considering many many different situations.

**Comment by yigit** [comment]
1) Depends on the library you are using. But it could be something like:
``` java
String imagePath;
String to; // receiving user id
onRun() {
     String url = storage.getUrlForImage(imagePath);
     if (url == null) {
          url = api.uploadImage(imagePath); // sync operation, should throw an exception on failure
          storage.saveUrlForImage(imagePath, url);
     }
     api.sendMessage(to, url); // sync operation,should throw an exception on failure
}
```

2) This depends on the UX you want to provide. One option might be to tag all send message tasks with a special tag and when user wants to logout, you can query job manager to see if it has such jobs and if so, let the user know that if they continue, you'll cancel those messages.
Alternatively, you can keep the authentication for that user inside the job so that when it runs, it will use that user's authentication (though this would be quite tricky).
