### ISSUE TITLE
Consumer is not created initially when JobManager is constructed in v1

### ISSUE THREAD

**Issue by ppong** [yigit/android-priority-jobqueue#155]
In v1 the JobManager set running = true in the constructor before calling start(). The start method returns immediately because running is set to true already. No consumers are created so pending jobs are not run.

**Comment by yigit** [comment]
JobManager knows there are pending jobs and creates queues to handle them. As long as you create the JobManager when your app starts, it should be fine.

**Comment by ben-manes** [comment]
Due to the above, it will only run the pending jobs once a new one is created. If jobs are not created frequently (e.g. due to certain user activity) then there is a long and unpredictable delay of when the job completes. When using job manager to manage offline updates this delay can be problematic.

**Comment by yigit** [comment]
you are right my bad. v1 has this bug whereas v2 handles this via idle callback.
Any reason blocking you from moving to v2 ?

**Comment by ben-manes** [comment]
Just priorities and we started on v1 prior to the v2 promotion. We had serious bugs in the [iOS task queue](https://github.com/thisandagain/queue) that @ppong fixed and then investigated if similar problems were in our Android one. For now we stop/start the job manager when initializing, which works fine. We couldn't tell if the problem was resolved in v2 when looking at the code, so thought it best to let you know if this use-case.

**Comment by yigit** [comment]
understandable, I appreciate the report.
FYI, V2 handles these via idle callback of the message queue:

https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/JobManagerThread.java#L248

I'm trying to wrap up v2 API to make it a release version

**Comment by ben-manes** [comment]
Then I think that if you have tests cases, you're welcome to close this whenever you feel appropriate. You may want to keep is around until v2 is officially released in case another user stumbles upon it.

**Comment by yigit** [comment]
v2 is out so time to close this :).
