### ISSUE TITLE
JobManager going SERIOUSLY MAD

### ISSUE THREAD

**Issue by LouisCAD** [yigit/android-priority-jobqueue#173]
Hi!
Sorry for the title, but below are the logs I got from my logger (which doesn't do much apart from calling Timber methods for logging. It cleared all the logs buffer in about 5 seconds on an Android KitKat device.

The output exceeds 65K characters, so I can't show it here, but see the impressive output in the file here:
[MAD LOGS AndroidPriorityJobQueue issue.txt](https://github.com/yigit/android-priority-jobqueue/files/293850/MAD.LOGS.AndroidPriorityJobQueue.issue.txt)

The configuration is the same as in my previous issue (#172), But I'm trying to use a custom serializer, using ByteBuffer manually (with no success yet).

**Comment by yigit** [comment]
hmm the following lines seems weird. It receives idle callback but next job query returns negative result which means there is already a job ready. This does not make sense because that job should come back in the query.

What happens if you don't add the custom serializer? Or is it possible for you to send me an app that reproduces the issue ?

`06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: flushing messages at time 1464796609402599521
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: [priority_mq] next delayed job null
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: [queue_RUN_JOB_RESULT_7] remove message null
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: [queue_CONSTRAINT_CHANGE_5] remove message null
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: [queue_ADD_JOB_2] remove message null
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: [queue_JOB_CONSUMER_IDLE_4] remove message null
06-01 17:56:49.393 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: joq idle. running:? true
06-01 17:56:49.403 7803-7826/net.suivideflotte.drivercompanion D/JobManagerLogger: Job queue idle. next job at: -9223372036854775808`

**Comment by LouisCAD** [comment]
You can see a better report, from the sample I sent you int #172 here: 
[FAT_LOGS Android-Priority-Job-Queue.txt](https://github.com/yigit/android-priority-jobqueue/files/295244/FAT_LOGS.Android-Priority-Job-Queue.txt)
