### ISSUE TITLE
JobQueue went crazy on some device.

### ISSUE THREAD

**Issue by malvinstn** [yigit/android-priority-jobqueue#187]
Hi,

Thanks for the awesome library.

I have one problem on the JobQueue on a specific device.
JobQueue went crazy and resulting in the **phone** to crash and restart.
I've tested with 5 phones, and the one that's having this problem is OnePlus One on CM13.1s.

[Attached trimmed log](https://github.com/malvinstn/test_jobqueue/blob/master/queue_log.txt)

When I count the log, there's 3,000 lines printed in a space of 1s.

I've created a test repo here.
[test repo](github.com/malvinstn/test_jobqueue)

Any advice?

**Comment by yigit** [comment]
hmm there is very little in the logs. seems like the JobQueue is woken up by the job scheduler.
I wonder if it is some bad implementation of JobScheduler on the CM side :/. 

You've only attached 120 lines of code. By any chance, can you enabled Ln.v as well and then post a larger log (preferably with alpha4)

**Comment by malvinstn** [comment]
I've updated the log to show more lines. Though I'm not sure by what you mean by alpha4 :|

Will specifying scheduler using `.scheduler()` help?

**Comment by yigit** [comment]
by alpha 4, I meant use version 2.0 alpha 4 which was released right then.
e.g. `compile 'com.birbit:android-priority-jobqueue:2.0.0-alpha4'`

Not sure what you mean by using `scheduler` but this setup looks fine.
https://github.com/malvinstn/test_jobqueue/blob/master/app/src/main/java/com/malvinstn/testqueue/MainApplication.java

Btw, your verbose logs are not handled, can you log them as well?

**Comment by malvinstn** [comment]
By `scheduler` I meant `JobManager.Builder.scheduler(Scheduler scheduler, boolean batch)`

I've updated to `alpha-4` and seems like it's a lot tamer, I've updated the log as well to handle verbose. Though I'll do some more testing to be sure.

**Comment by malvinstn** [comment]
Oops, spoke too soon. My device still restarts itself after a few mins...

**Comment by yigit** [comment]
do you have longer logs ?

**Comment by malvinstn** [comment]
By longer do you mean longer format? or do you need more lines? I think I can get ~ 6,000 lines before the device restarts itself.

**Comment by yigit** [comment]
yep, whatever lines you can grab.

**Comment by malvinstn** [comment]
I've updated the log with 6,000+ lines. It's at the same link as above.

**Comment by yigit** [comment]
thanks a lot. i'll try to check them tonight and see if I can reproduce.

**Comment by yigit** [comment]
hey, haven't looked at the log yet but just wanted to ask for one more information which may include why device restarted (because even thought job manager goes crazy, it cannot easily restart the device).

Can you grab a bug report from the device right after restart?
Thanks.
`adb bugreport > mybug.txt`

**Comment by yigit** [comment]
ok seems like JQ keeps re-scheduling a job and then finishing it. Finish sends a onFinished callback, JobManager thinks there are more jobs matching the constraint and reschedules :/. And this goes on and on.
I'll debug to see why this is happening.

Thanks a lot btw, this is very helpful.

**Comment by malvinstn** [comment]
No worries,

I've added the `adb bugreport` [here](https://raw.githubusercontent.com/malvinstn/test_jobqueue/master/bugreport.txt). Hope it helps.

**Comment by yigit** [comment]
Ok i cannot reproduce the error with the sample app but I'll try to create a unit tests from the logs.
Also, the bug report unfortunately didn't help but thanks for sharing it. (for some reason its format is not recognized by the bug reader tool but that might be because it is cynogenmod)

**Comment by yigit** [comment]
Ok i think i found it in the logs.

`06-21 17:01:30.059 4934-4953/com.malvinstn.testqueue D/MainApplication: [FW Scheduler] scheduled a framework job. Success? true id: 1 created id: 2046`

This is the line where JobScheduler schedules a JobService job.

And this is when it is executed (callback from the framework):
`06-21 17:01:30.071 4934-4934/com.malvinstn.testqueue D/MainApplication: [FW Scheduler] start job SchedulerConstraint{uuid='ba4d5780-85eb-4c15-b6bf-7daa76238ee2', delayInMs=900000, networkStatus=1, overrideDeadlineInMs=null, data=null} 2046`

As you can see, the job has 900000 ms delay (15 min) but it is executed almost instantly in less than a minute. When that job arrives, JobQueue cannot find any job to handle but knows that there are jobs matching the criteria so reschedules it. Then this goes on and on.

At first i thought this is a bug in CM but turns out it is a FW scheduler bug. I'll push an alpha5 so that you can quickly test it. I definitely need to add more tests around the FW and GCM schedulers. :/

**Comment by yigit** [comment]
ok i've pushed alpha-5 . Please give it a try and lmk if it fixes the issue. 

Thanks for the detailed reports.

**Comment by malvinstn** [comment]
Hi, tested alpha-5 and it works smoothly so far.

Thanks a lot for the fix. Happy to help! :smile:

**Comment by yigit** [comment]
amazing, lmk if it re-surfaces. Thanks!
