### ISSUE TITLE
Make JobManager#count() callable on the UI thread

### ISSUE THREAD

**Issue by LouisCAD** [yigit/android-priority-jobqueue#193]
Hi,

I would like to be able to show the pending jobs in the JobManager in the settings of my app. However, the code I need to write to make this work is spaghetti like because `count()` is not callable on the UI thread, and using a `JobManagerCallback` to get notified when a job is done or added to update the pending jobs count shown in the UI is overkill.

Why the JobManager don't just increment an internal int field named `count` each time `addJob(...)` or `addJobInBackground(...)` is called, and decrement it when a job is done or cancelled, using possibly an AtomicInteger if these events (job added, done or cancelled) are not synchronized on the UI thread?

And any advice on how to listen for count changes with the simplest code possible?

**Comment by yigit** [comment]
It is not callable on the UI thread because it makes a disk query.

With all cancelations, delay, single-top jobs etc, it is not trivial to keep such a variable internally so if I were to implement it today, I would be writing it on top of callbacks as well. So unfortunately, thats your best option.
We can provide an async version of the count method if you prefer.

**Comment by LouisCAD** [comment]
Yes, an async version, if coupled with a callback to receive changes would help.

BTW @yigit What are single top jobs exactly, and how to make one?

**Comment by yigit** [comment]
sorry I meant single id:
http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/Params.html#setSingleId-java.lang.String-

**Comment by LouisCAD** [comment]
@yigit What's the behavior with single id? Any new job replace the previous in the queue, ensuring only one job in queue?

**Comment by yigit** [comment]
Yep. This is good for cases where you have a Job to sync something local to the server and you don't want to have multiple instances of it.
Here is the related PR: https://github.com/yigit/android-priority-jobqueue/pull/106

**Comment by LouisCAD** [comment]
This is worth special mention in both the wiki and the README. I found myself accumulating same request to update the same thing because network was unavailable. Would you want me to do the doc for this and submit a PR?

**Comment by yigit** [comment]
sure I would love to have that. If you create a PR, please cc @guavabot for review.

**Comment by LouisCAD** [comment]
BTW, I think that single instance jobs shouldn't be counted in as this is mainly used to refresh some info I guess (correct me if I'm wrong)

**Comment by yigit** [comment]
You are just thinking about your use case :) The count is not really intended to be shown to the user.
The api just counts number of jobs so any job should be there.

**Comment by LouisCAD** [comment]
But did you think of the troubleshooting case where the user needs to check that no jobs are pending in the queue? How to let the user make sure his tweet is sent, or that an important task has finished run successfully?

**Comment by yigit** [comment]
You cannot rely on a global number like count for anything related to UX because it will start behaving differently as soon as you add more types of jobs for different activities (which are not necessarily related to the UX).
We provide an API to get the status of a job which you can consider using in conjunction with the callback class.
Indeed, tests use a similar code to watch for particular jobs to finish.

https://github.com/yigit/android-priority-jobqueue/blob/c203793f8d27ba84c5ba5a147fa4212859463830/jobqueue/src/test/java/com/birbit/android/jobqueue/test/jobmanager/JobManagerTestBase.java#L274
