### ISSUE TITLE
Document behavior if multiple JobManager are created

### ISSUE THREAD

**Issue by LouisCAD** [yigit/android-priority-jobqueue#195]
Hi,

I wonder what happens if multiple `JobManager` instances are created, especially if Jobs are persisted and if there's `GcmNetworkManager` or `JobScheduler` integration.

My guess is that it would cause inconsistent behavior because jobs would be stored at the same place for both JobManagers. Shouldn't JobManager be a singleton to ensure this can't happen?

Can you put some light on this please?

**Comment by yigit** [comment]
Nope, this is also why you have to manually integrate with Schedulers rather than JobManager doing it for you. It is valid to keep multiple JobManagers. If you are integrating each of them with the scheduler, you'll be creating a service for each of them.

JobManager does not use the schedulers to keep the Job data. Indeed, by default, not all of your Jobs go to the scheduler. By default, uses a batching scheduler such that if you 5 jobs with the same constraints, it will call scheduler just once to wake up the JobManager then JobManager calls it back once all of those jobs are done.

Even if you have multiple JobManagers, since the Scheduler will wake up the correct service (and there is a 1-1 mapping w/ the Service and JobManager instance) it will wake up the correct JobManager.
This is by design.
