### ISSUE TITLE
Job result delivery

### ISSUE THREAD

**Issue by mecid** [yigit/android-priority-jobqueue#20]
I have an architecture problem. Some of my jobs save result to db and CursorLoader automatically update UI. What about result which not saved to db, i am using eventbus to notify UI about job work finishing, but how can i deliver result?

**Comment by yigit** [comment]
Well, it depends on your use case.
Sometimes, just dispatching the event with the result data is enough. Maybe it is some important event that should be displayed to the user and in that case, you can use sticky events (assuming it is singleton). When it is a sticky event, your activity should check it in onResume to recover it.

If it is more complex but you still want to keep the information, you probably need a controller class which handles job lifecycle, keeps data and can provide the information to the activity when needed. This way, you can also recover the information after configuration changes(similar to sticky events but more flexible). 

Sometimes, maybe all you want is a non-persistent job with a callback that you can call when job is finished. In this case, you need to be careful about not leaking the activity. This is generally achieved by keeping a weak reference to the callback from the Job and a strong reference from the activity (callback lives as long as activity lives).

If you can provide a more detailed example (including use case), I may be able to provide better information.

**Comment by mecid** [comment]
@yigit i am working on twitter client.

User can search tweets or other users by keyword. This is a non-persistent job result should not be saved to db, but very important for user.

**Comment by yigit** [comment]
There are a couple of options. A simple approach would be to create a listener, pass it to the job (job holds a weak reference to it,  activity also keep a strong reference to it) This ensures connection lives as long as activity lives). This would be like using JobQueue to run an Async task.

Another potential option is to use sticky events where job posts the result as a sticky event and Activity listens for it. This is better because it helps you recover the response. But of course you need some mechanism to destroy the event not to keep all results in memory.

If you have live search (search while user types), you would need something more complex. You could have some sort of `manager` class that is responsible to control these search queries and results.

When you want to search something, you would call this `SearchManager#search( text)`. This would enqueue a job which holds the text. When Job's `onRun` method is called, it calls `SearchManager#isCurrent(text)` to make sure it has not been overridden. If it is no more the text, job simply ends without doing any server call. If it is the current text, job makes the API call and when response arrives, calls `SearchManager#onSearchResult(text, results)`. Again, when onSearchResult is called, `SearchManager` check the text is the latest text and dispatches an event. Maybe also keeps the latest response.

On the activity side, activity listens for the event and when event arrives, calls `SearchManager.getResults(text)`. In this case, the text is passed from the TextView to ensure it is what user is seeing. 
Although slightly more complex, this would work better because when activity is restored, you get the text from TextView (it will automatically save that state) and check with SearchManager if the result arrived while activity was dead. When your activity is destroyed, you call SearchManager to clear the cache.
Of course, SearchManager could get more clever and keep search results from last few words. You can even further enhance user experience by querying this data locally as well to dispatch a fake ResultReady event while the actual job is running. 
You are churning some jobs here, which is not too bad and if you really care about it, you can do it by keeping the information about last job in the `SearchManager`.

Hope this is helpful.
Lets say user is searching for `SF Giants` account, as soon as user puts, `SF Gian`, the giants will show up in results so doing this local search would keep that result visible, making it a lot user friendly. Of course, you should still call the server to get actual results, be careful with synchronization etc but implemented well, this would be a decent user experience.

**Comment by mecid** [comment]
Thanks)
