### ISSUE TITLE
Jobs with Views

### ISSUE THREAD

**Issue by egrgdam** [yigit/android-priority-jobqueue#211]
Hi,

I'm new to JobQueue and I tried to google any relative info about putting view components in Job subclasses. I'm trying to create WebView instance and run WebView methods inside Job onRun() method. Is it even possible, or I have to implement some kind of activity handler or some other methodology?

PS: I know that WebView component is GUI component and should run on main thread, but my use cases require that it runs in background thread.

PSS: Know also that this question is not issue and shouldn't be here on GitHub (currently cannot access stackoverflow)

Thanks,
BR,
G

**Comment by yigit** [comment]
It is very dangerous to have Jobs that keep a reference to an activity context due to potential for leaks. You may want to implement an [ActivityBoundJob][1] so that you instantly cancel a job if an activity is gone. Besides this, you cannot make that job persistent since Context cannot be persisted.
Since this is an uncommon use case, there is no convenient way to do it. You have to pass the activity context to your job via constructor parameters or via a dependency injector.

[1]: https://github.com/yigit/android-priority-jobqueue/wiki/Canceling-Jobs#canceling-jobs-of-an-activity

**Comment by egrgdam** [comment]
Thanks for prompt answer! I'll go back to use hack with webview from service component.
