### ISSUE TITLE
Does the job keep running even after app is closed...

### ISSUE THREAD

**Issue by bhargavms** [yigit/android-priority-jobqueue#217]
and does it restart if a job fails due to network down, and restart when the network's up again even though your app isnt running, if not how do I get it to work like this ?

**Comment by yigit** [comment]
Job cannot run if app is closed because it runs in the app's process.
If you are referring the app going to background by "closed", yes jobs will run when the app is in the background.

If the app is terminated while you had a persistent job that requires network, by default, JobManager cannot wake up the application when network is recovered (unless you have a Network broadcast receiver defined in the XML but that won't work in `O` as android deprecated it).

For this use case, JobManager offers integration with job scehdulers that are provided by the framework and the backport (GCMNetworkManager).

You can check the [WIKI](https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager) to set it up for your application.
Once you integrate, JobManager will use these schedulers to wake up the application when the network is available.

The sample app also has that [integration](https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/src/com/birbit/android/jobqueue/examples/twitter/TwitterApplication.java):

**Comment by bhargavms** [comment]
Basically what I was trying to get at from this question is that, does the job api behave like the Service api with START_STICKY flag?? Where in even after you go to recent apps and swipe close your app, the service still keeps running
