### ISSUE TITLE
Job object didn't serialize after onAdded call for persit job

### ISSUE THREAD

**Issue by AlexandreGorobets** [yigit/android-priority-jobqueue#240]
The problem:
We want to store some private data in job fields at onAdded call 
But job serialization is called only afrer job created (before onAdd call) and on handleRunJobResult (after onRun call)

So if our job removed from memory between onAdded and onRun - all modified data (object fields) will be lost.

**Comment by yigit** [comment]
This is by design. You should calculate that information when job is created, not when added.
`onAdded` gives you the guarantee that the job will be run. If you modify the job, there is no guarantee that the information will be preserved (vs there is a guarantee that all information will be preserved that was calculated before `addJob` is called).

Can you add more details ? Why can't you calculate this in construction ?

**Comment by AlexandreGorobets** [comment]
1. Yes, I can do it at constructor. But anycase this behavior is not clear to developer. Because I see that fields persist after constructor and between calling of onRun (in case of error retry). But not saved after another api methos (onAdded)

2. Any constructor work will executed on MainThread (in most cases) and any addidtional Job initialization will be not good

You create workaround this situation in your example by generating Db id like timestamp:
https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/src/com/birbit/android/jobqueue/examples/twitter/
jobs/PostTweetJob.java
But it can't be done by using db-generated id's.

I didn't see any potentional problem by implementing storing job (for persit job) after onAdded. 

If you think that serializing job is to heavy, you can turn it on by special option in configuraton that will be off by default. 

Another solution - you can add something like Bundle (that store primitives) that developer can use to store variables between job state changes constructor -> onAdded -> onRun -> (error) -> onRun
This bundle (state object) will be more light to serialize and deserialize

**Comment by yigit** [comment]
re-writing after calling `onAdded` is not the problem. The problem is that `onAdded` comes with an API promise  that Job's data is persisted and will be available in `onRun`. If we were to persist it after `onAdded` we could not give any guarantee on whether the data is saved or not since the app might crash between `onAdded` return and before it is saved.

`onAdded` is the checkpoint we return to the app about the fact that job's data is persistent and it is guaranteed to run. Also, `onAdded` is not guaranteed to run if app crashes after job is saved to disk before `onAdded` is called. 

What are you trying to achieve? Maybe you can generate some UUID in the constructor and use it in `onAdded` or `onRun` ?
Can you add more details about your case?
