### ISSUE TITLE
[Question] Multi-Process JobManager

### ISSUE THREAD

**Issue by danysantiago** [yigit/android-priority-jobqueue#256]
Hey,
Thanks a lot for the great library.

I was wondering if its possible or if it even makes sense to use the JobManager across different processes. More specifically, I would like to declare my JobService in a process and post jobs to it from a different one. 

My initial approach is to send intents to the JobService with the necessary information for the service itself to add the job to the JobManager, but I'm curious to know if that is a reasonable approach.

Thanks!

**Comment by yigit** [comment]
That is an interesting idea and totally valid if you want to have a better chance of your jobs running when your app process is killed since app process is likely to keep more memory (activities in background etc).
But of course by doing this, you'll be losing your ability to easily share memory and events w/ jobs. It depends on your architecture :/.

Base Job class is not Parcelable so you cannot pass it through IPC. You'll need to pass necessary job information via IPC and construct the job in the runner service.

I would not advice doing this by default but if you have a compelling reason, go for it. Just make sure you do not initialize the JobManager in both processes. Maybe you can have 2 job managers (with different ids) for the main process and the service process.

**Comment by danysantiago** [comment]
So, I'll share my use case to give you some insight, let me know your thoughts.

I have a MediaBrowserService, a long running sticky service that lives in a different process from the UI and from where the JobService is declared. The ability to host the Music Service in a different process enables us to have a very lightweight music app. The UI client is the heavy user of the JobService since it queues all sorts of jobs, plus, as you mentioned, being in the same process enables us to share the same memory, events and even dependency injected objects.

However, this music app has a radio feature, which means we plays a few songs and when we finish playing a song list we go ahead and fetch more songs. Now, consider how the UI & JobService process can be killed while the Music process is still around, it would be nice if we could schedule a Job to be executed in the JobService, starting its hosting process along with the service to handle the job and return us the result. Something we would do when fetching more songs.

It is important that only the UI and JobService process makes the api calls since auth tokens, encryption and a few other api related state are stored in SharedPreferences (which is not multi-process friendly). Only a single process should handle re-auth, making sure to retry other failed api calls. Moreover, the job has to be properly schedule in the event that other jobs are also scheduled, in terms of priority.

I think for now, the approach of sending intents to the JobService for it to create the job itself and enqueue it works well. The result reaches the Music Service back through an intent. But it seems kinda tedious and I lose some functionality, such as cancelling and retrieving a job's status.
