### ISSUE TITLE
Custom Persistence Handling

### ISSUE THREAD

**Issue by viralmoonlight** [yigit/android-priority-jobqueue#265]
Hello,

Great Work on the library.

I am using couchbaselite database as my primary local database for my android app. But to schedule jobs I am using this library and would like to know if there is a way to implement a custom persistence model for jobs instead of using the underlying sqlite? 

Thanks

**Comment by ckirkman** [comment]
Sure - if you implement a custom [JobQueue](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/JobQueue.html) you can use it instead of the default [](http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/persistentQueue/sqlite/SqliteJobQueue.html).

That said, you can use the default SQLite database alongside your couchbaselite database unless you have a specific reason to consolidate. I use Realm as my primary database but keep this library using SQLite without any issues (performance or otherwise).

**Comment by ZakTaccardi** [comment]
There's nothing wrong with letting these jobs be serialized in SQLite and have your couchDb serialized the rest of your data

**Comment by viralmoonlight** [comment]
@ckirkman @ZakTaccardi Hey guys thank you for getting back. 
Yes, I decided to use both couchbaselite and SQLite since the SQLite persistence is not bad on storage for the jobs.
