### ISSUE TITLE
Resume a job

### ISSUE THREAD

**Issue by alfdev** [yigit/android-priority-jobqueue#266]
Hi,

It's possible to resume a job? 
And so when it start again i can restore the situation when it previously stopped.

Thanks

**Comment by yigit** [comment]
What does it mean to resume a job? JobManager does not stop an already running job. Are you referring to a case where the job crashes while executing?

**Comment by alfdev** [comment]
I mean while the job is executing in certain situation i have to stop the job and resume it when that situation change again.

**Comment by yigit** [comment]
If the Job fails, JobManager re-serializes the job to disk so if you are stopping the job by throwing an exception from onRun, it should work as you expected.

**Comment by alfdev** [comment]
So you are saying that i have to throw an exception?

**Comment by yigit** [comment]
how else are you stopping the job ?

**Comment by alfdev** [comment]
You're right, i already throw an exception when the device has no more network. But when the job run again my index property starts from 0 and not where the job has stopped.

**Comment by yigit** [comment]
It has to start from where the job stopped. We cannot record the stack trace. But your fields will be saved.

**Comment by alfdev** [comment]
Ok, i make same other tests.

Thanks yigit

**Comment by ofermoshsaioff** [comment]
piggybacking on this question, when a job fails due to a crash, or if the user just leaves the app and the process is killed, what would you say is the best approach to **immediately** re-run the (persistent) job without waiting for the user to open the app again? I suppose using a service is the best approach, but in that case, I would also have to stop the service somehow when the job has finished and there aren't any callbacks for that. I also thought about running a "clean-up" job after every job that would take care of that, but there's no real way to know if there are any jobs currently running..

**Comment by yigit** [comment]
i think this is answered in #273 .
