### ISSUE TITLE
Rerun an unfinished Job immediately after the process is killed

### ISSUE THREAD

**Issue by ofermoshsaioff** [yigit/android-priority-jobqueue#273]
Hi @yigit thanks for creating a great library! 

I'm using this mainly for persistent tasks that require UI updates like uploading images and showing a notification in the status bar indicating the upload's progress, so far so good, looks great!

The problem starts when I want to recover right after the process was killed, meaning I want the Job to restart itself **immediately** after the process was killed. I've wrapped the `JobManager` inside a `Service` with the `START_STICKY` flag, which does what I want, but this keeps the Service and the process up forever, and I don't want that either. I need to find a way to somehow stop the service when the JobQueue has emptied, but there's no easy access to it really, and I understand this is by design to avoid misuse.

I also tried inserting a "cleanup" Job that will stop the service after every Job, but this becomes harder to manage when there are several pending Jobs in the queue.

I can try using an `IntentService` but I don't want to lose the ability to run multiple jobs in parallel. 

What is the the better option here?

**Comment by yigit** [comment]
I would suggest 2 things:
a) Don't fight against the OS :). Putting JobManager inside a service and keeping the service running as long as there is a job seems like a good indication to the OS. You can get notified about jobs using a JobManagerCallback.
b) Integrate with the [schedulers][1] so that the app can wake up to complete any pending job.

[1]: https://github.com/yigit/android-priority-jobqueue/wiki/Integration-with-JobScheduler-and-GcmNetworkManager

**Comment by ofermoshsaioff** [comment]
thanks @yigit for the info. I tried using the `JobManagerCallback` and for the most part it works fine, but still doesn't cover me in the following scenario:

I've wrapped the JobManager inside the (sticky) service as mentioned which really serves as a watch dog for the JobManager, it's sole purpose is to re-initiate the JobManager after the process was killed which will in turn re-run any pending jobs it had persisted. I'm using the callbacks to start or stop the service accordingly, i.e. start the service when `OnJobAdded()` is called and stop it when `onJobRun()` is called providing there are no more pending jobs of course (using `JobManager.count()` for that). 

1. job A is added
2. starting service when `onJobAdded()` is called
3. job B is added
4. job A has finished.
5. job B has started (notice `onJobRun()` for job A wasn't called yet)
6. `onJobRun()` called for job A - stopping the service (at this point the `JobManager.count()` method returns 0 as the B job is already running)
7. killing the app process

In this case the service will not restart itself because we've explicitly stopped it and haven't started it again. Using my own counter to track the current # of running jobs and only stopping the service when there aren't any does the trick but I feel this is a bit of a hack and could also be potentially buggy.

**Comment by yigit** [comment]
That is because [count][1] does not include running jobs.

You should instead use pair of [onJobAdded][2] and [onDone][3] and count it yourself.

[1]: http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/JobManager.html#count--
[2]: http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/callback/JobManagerCallback.html#onJobAdded-com.birbit.android.jobqueue.Job-
[3]: http://yigit.github.io/android-priority-jobqueue/javadoc/com/birbit/android/jobqueue/callback/JobManagerCallback.html#onDone-com.birbit.android.jobqueue.Job-

**Comment by ofermoshsaioff** [comment]
Yeah, that's what I did eventually. thanks again
