### ISSUE TITLE
How to replay onRun()

### ISSUE THREAD

**Issue by anthony3444** [yigit/android-priority-jobqueue#274]
Hi!

In my job I call (**synchronous**) a web service through **Volley**. Sometimes there is a **TimeoutException** which appears with no reason ... 

So, I would like to replay onRun() method if this error is catched.

How to do this ?

```
@Override
    public void onRun() throws Throwable {
        mWebServiceMgr.provideRestApiTraining().addTrainingExercise(
                        new RestApiTraining.OnAddTrainingExerciseListener() {
                            @Override
                            public void onAddTrainingExerciseResult(RestApiBase.ResultCode result) {
                                // OK
                            }

                            @Override
                            public void onAddTrainingExerciseFailure(GenericException e) {
                                // FAILED ! I WANT TO REPLAY THIS WEB SERVICE !
                            }

                        });
}
```

Thank you very much guys!

**Comment by yigit** [comment]
Let it throw the exception, jobs are re-tried automatically (by default 20 times). You can also implement shouldReRun to add back-off, change priority etc.

**Comment by anthony3444** [comment]
Ok fine! Another question: imagine there are 2 different jobs in the queue with the **same** group:

`super(new Params(Priority.HIGH).requireNetwork().persist().groupBy(GROUP));`

The first job failed due to ws service exception. The second job is sent or the first job is retry (20 times max) before to run another job in this group ?

**Comment by yigit** [comment]
JobManager always respects the priority so if you have job A & B with the same group and priority, and both are available to run, whichever is added first has to finish before the other one is allowed to run.
So if A is added first and fails, it will be retried instead of B.
You can change it in `shouldReRun` method by either adding delay(a.k.a. back off) or changing its priority.
So if you add back off to A, B will be the only available job in that group so it will run (assuming no other jobs).
Or if you de-prioritize it in shouldReRun, B will have a higher priority and will run.

**Comment by anthony3444** [comment]
Ok thank you very much for your help!
