### ISSUE TITLE
Do I need to migrate persistent jobs if I'm migrating from v1 of this library to v2?

### ISSUE THREAD

**Issue by ApoorvKhatreja** [yigit/android-priority-jobqueue#310]

**Comment by yigit** [comment]
yes, unfortunately, v1 and v2 are not compatible.

**Comment by ApoorvKhatreja** [comment]
@yigit Would you recommend forking the library and then handling the migration myself in the `DbOpenHelper` or keeping around both versions of the library, and then doing a one time in memory migration by loading old jobs one by one, creating new jobs based on them and adding them to the new `JobManager`?

**Comment by yigit** [comment]
jobs use different packages so i would recommend keeping both, give a new ID to the new one (so it uses a new database file). Initiate the old job manager but never add jobs and eventually remove it after a few releases.
I don't think more work than this makes sense since it is unlikely that users will have pending jobs.
