### ISSUE TITLE
Group by Id

### ISSUE THREAD

**Issue by sakismts** [yigit/android-priority-jobqueue#317]
Hi 

I am creating two different jobs. I want to group them with the same group id but I want the first job to run first and the second job to run after the first one.   When I configure the two jobs I am adding the parameter. setgroupId("1") and I am setting the priority of the first job to 1000 and the priority of the second job to 500. I also have the network required parameter. When I go from offline to online the second job is executed first and the second after. Am I doing something wrong?

Thank you

**Comment by yigit** [comment]
That should never happen. JobManager guarantees that if 2 jobs are in the same group, the one with the higher priority will run first.
You may be hitting a race condition if you are adding lower priority job first because when you add it, there might be an available consumer which will pick it up and run it.
Make sure you are adding the higher priority job first in the same thread as the lower priority job and JobManager will guarantee that the higher priority one will run first.
