### ISSUE TITLE
Execute jobs in serial

### ISSUE THREAD

**Issue by Sharjeelh** [yigit/android-priority-jobqueue#345]
I have added three jobs in jobManger to execute them in serial(wait for first job to finish to start second and so on) and set the same groupId for all of them but jobs don't run in a serial. 

        jobManager.addJobInBackground(new FetchQuestionsJob(this));
        jobManager.addJobInBackground(new FetchUsersJob(this));
        jobManager.addJobInBackground(new FetchTeamsJob(this));

**Comment by kingargyle** [comment]
You might need a new JobManager that is single threaded.   Or you could, add the next job to run in the onRun methods.   So if FetchQuestionsJob needs to run first, then in hte onRun, you can add FetchUsersJob... etc. etc.

That way they'll only be added to the queue and execute after the other one has been completed.

**Comment by Sharjeelh** [comment]
Can you please take a look at following stack and suggest something
http://stackoverflow.com/questions/43324886/run-jobs-in-a-serial-in-android-priority-queue

**Comment by yigit** [comment]
The problem is in your Job. Jobs must be sync but your job returns from `onRun` without doing its work so JobManager has no idea that it did not finish. If you make your jobs sync, they'll run sequentially.
And @kingargyle , no he does not need a single threaded executor, JobManager supports this out of the box.

**Comment by kingargyle** [comment]
@yigit yeah, I found that out later after doing some more reading on how Grouping is supposed to work. My mistake.
