### ISSUE TITLE
cancelJobsInBackground do not work on the second time

### ISSUE THREAD

**Issue by heitorpr** [yigit/android-priority-jobqueue#40]
Hey Yigit! (version 1.3.3)

I'm having a problem when I try to cancel jobs in background or in main thread also (cancelJobs). I'm trying to cancel the jobs every time I do a fetch on my collection. Like this:

```java
Application.getInstance().getJobManager().cancelJobsInBackground(new CancelResult.AsyncCancelCallback() {
            @Override
            public void onCancelled(CancelResult cancelResult) {
                collection.fetch();
            }
        }, TagConstraint.ALL, "get");
```
I am in a activity with several fragments that works like tabs. When I change from one fragment to another I try to update the collection in this way. That works fine when I do a change for the first time. But when I try again the cancelJobsInBackground do not give me an answer to my listener. And when I call the method cancelJobs instead, it appears to be in a eternal looping, also appearing the popup of android to close the application because it do not responds anymore. I will avoid using cancelJobsInBackground for now on. Thanks in advance.

Heitor.

Obs.:
- collection.fetch(); init a job that do a complex work on background (using a database and after a call to the API).
- Jobs are working very well! But the cancelation of them...
- Perhaps I'm doing a bad use of the library, any suggestion would be great =D

**Comment by yigit** [comment]
This is bad implementation on my end because I shouldn't sync on `this` on main thread. Can you send me a thread dump when this happens? Or any app to reproduce the issue would help.
It is possible that your cancel result does not arrive while it is waiting for a job to finish but it should not be blocking main thread. Fyi sync happens around creating the executor so I believe another sync block is locking this. 

I would be very happy if you can provide a thread dump. (btw, sorry for the late reply, I just came back from a long vacation).
