### ISSUE TITLE
creating a unique job

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [yigit/android-priority-jobqueue#433]
what happens if a job with same Id already exists ?
I want to have only job with the same Id. when i try to add a new job with same Id then the old job should be replaced with new one .

How can i create a job with unique Id ?
Is there anything like setUnique(true) for a job ?

**Comment by kalpeshp0310** [comment]
You can create a Single Instance Job using `singleInstanceBy(String instanceId)`. have a look at [Single Instance Jobs](https://github.com/yigit/android-priority-jobqueue/wiki/Job-Configuration) section.

Note: You need second job to replace older job. but library will cancel second job if there is a job in queue with same instanceId, instead of replacing it.

**Comment by kpradeepkumarreddy** [comment]
I'm using the following piece of code to ensure that a job is not running with same id.
Is this the correct way to do it ? 
 
```
JobStatus jobStatus = Jobmanager.getJobStatus("ID");
 if (jobStatus.ordinal() == JobStatus.UNKNOWN.ordinal()) {
          Jobmanager.addJob(new Job());
  }
```

**Comment by kalpeshp0310** [comment]
Yeah, this approach also works. Only thing to note is that you have to run this code on non main thread, other wise it may cause UI jank.

**Comment by kpradeepkumarreddy** [comment]
Thanks.
