### ISSUE TITLE
interdependent jobs  - queues vs rxjava ?

### ISSUE THREAD

**Issue by sandys** [yigit/android-priority-jobqueue#61]
hi yigit,
I have gotten most things to work (including dagger2) and it works great!

however there is a pattern that I'm not sure how to address:
I have to upload 3 heavy files to an API . after each upload, I get a url of the file. After all three files are uploaded, then I have to call an API with the urls of the three files.

One way to think about it is use something like rxjava and combine observables. Second way is to have one job fire three file upload jobs. but this means the parent job will go back to sleep and wait till the other three jobs are done. 

I'm not very sure of the right way to solve this. how would you do this ?

**Comment by sandys** [comment]
I'm seeing one pattern where you are able to track interdependent states using the constructor of the job.. or the onAdded hook, but it is not clear how you do this among groups of jobs...

**Comment by yigit** [comment]
This depends on your use case a lot. Specifically about what happens if you can upload 2 files and your system shuts down your app?
If you don't care about losing work in this case, RxJava's API is probably better. If you are already using Rx, create an RxExecutor that can run any RxRunnable (or whatever they call them, I don't know the API) on the JobQueue so that you share threads.
If you are not using Rx and your Jobs are NOT persistent, just pass a listener to all of them and when the last one finishes, create the upload Job.

If you do care about persistence, afaik Rx does not provide a solution for that (but again, i've never used Rx so I might be wrong). A possible solution with JobQueue would be to have a thread safe central location which keeps track of the progress (probably using shared preferences so that they can be persistent).

Each of these upload jobs will call this central location after successfully uploading a file (or on Cancel if it fails). 
When all upload jobs are finished, this central location can create the other job which will post the result.

This additional job creation step is kind-of ugly, you can instead create all of these jobs with the same `groupId` and give a higher priority to the file uploader  jobs. The downside is that they won't run in parallel. The upside is that you create all 4 jobs and forget about it. JobManager will guarantee calling the new Job after the other 3 completes. If you want jobs to back-off, just make sure you apply backoff to the group to preserve the priority.
https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/path/android/jobqueue/RetryConstraint.java#L98

**Comment by sandys** [comment]
hi,
thanks for the reply.
Yes - I'm using RxJava. In fact the solution I have right now is to construct an observable with all the jobs in the right dependent order. Obviously, as you mention... there's no guarantee against failure.
I like your suggestion of creating the 4 jobs with the same groupid. what I'm unable to figure out is how to synchronize data between them: the fourth job needs the output of the other 3 jobs. What would you suggest ?

**Comment by yigit** [comment]
Do you want to handle job failures & app restarts (e.g. are your jobs persistent)? (answer depends on that)

**Comment by sandys** [comment]
Hi,
To simplify things - the answer is No (don't need persistent jobs).

However - and this is important- I want to know about failures (and I will
show something to the user on the basis of that). I think most apps will
follow this model.

**Comment by yigit** [comment]
O, may something like this will work fine:
```java
    class ProgressTracker {
        List<String> uploadedUrls; // assuming output of an upload job is a url
    }

    ProgressTracker tracker = new ProgressTracker();
    String groupId = UUID. randomUUID().toString();
    jobManager.addJob(new UploadJob(new Params(2).groupId(groupId).requiresNetwork(), tracker, url1);
    jobManager.addJob(new UploadJob(new Params(2).groupId(groupId).requiresNetwork(), tracker, url2);
    jobManager.addJob(new UploadJob(new Params(2).groupId(groupId).requiresNetwork(), tracker, url3);
    jobManager.addJob(new UploadResultJob(new Params(1).groupId(groupId).requiresNetwork(), tracker);
```

UploadJob looks something like this:
    
```java
    onRun() {
         // do work
         tracker.addUrl(mUrl);
    }

    shouldReRunOnThrowable(Throwable t, int runCount, int maxRunCount) {
         RetryConstraint constraint = RetryConstraint.createExponentialBackoff(runCount, 1000);
         constraint. setApplyNewDelayToGroup(true);
         return  constraint;
    }

   onCancel() {
        tracker.addFailedUrl(mUrl);
   }
```

And UploadResultJob looks like this:

```java
    onRun() {
        if (tracker.failedUrls.isEmpty()) {
              // upload the result, then publish an event with the result.
        } else {
             // publish and event with the error
        }
    }

    onCancel() {
        // publish and event with the error
    }
```

Keep in mind that, since the user may leave the activity before uploads complete, you should have another EventHandler that will post a notification instead. (or something similar, really depends on your app)

**Comment by sandys** [comment]
this is awesome!

what I'm thinking is that I can use Dagger to create a ProgressTracker instance and use it to maintain the records.
thanks for your help!

**Comment by sandys** [comment]
One question though - what happens if app closes. The jobs will be
persistent... Will the shared data structure also be persistent (and
shared)?

**Comment by yigit** [comment]
Wait, you said you don't want to persist jobs?
You need to decide about this. If you make your jobs persistent, the logic above **wont** work because each job will serialize a copy of the Tracker. If you want persistence, create a singleton ProgressModel which can track progress per UUID (that you've used to create the job groups). Then jobs can update the progress in the ProgressModel using the UUID and the ProgressModel will take care of persistence (shared pref?).
