### ISSUE TITLE
I can't find a job with jobmanager

### ISSUE THREAD

**Issue by mahuafactory** [yigit/android-priority-jobqueue#67]
I have read all the code,I found that,there's some method can find a job by tag or id.But I can't find it with Jobmanager,because some members are private.I can't use them directly.

Sometimes , like a download job,when I have left my app's activity for a while,and then I'm back.I want to know has the download job done.I want to find the job by some tag,and read it's status.

**Comment by yigit** [comment]
I intentionally don't provide such an API because it is recipe for many issues.
For why I don't, see my answer here: http://stackoverflow.com/questions/34379914/retrieve-current-list-of-active-jobs-in-android-priority-jobqueue/34387692#34387692

For your use case, a proper design would be to have some model class that keeps the information. Job would keep updating it as it progresses and also dispatch an event to notify the progress has changed.

Then you can always query this model and also get notified when it is changed.

**Comment by mahuafactory** [comment]
THX,I think I understand this.THX
