### ISSUE TITLE
Async execution within one Job?

### ISSUE THREAD

**Issue by lemonboston** [yigit/android-priority-jobqueue#95]
Hi,

I am playing with the library and I think it is awesome.

I have only one use-case concern: How to execute calls in parallel as part of a single Job?
Example: To find out which of two cities has higher temperature currently I would call getTemp(city1) and getTemp(city2) in parallel to have the result quicker.

I understand that the library is designed so that the work in Job's onRun() is synchronous, and multiple Jobs are executed in parallel but using that for this use-case would mean the need to save some extra state somewhere.

RxJava can handle this elegantly with something like this:
```
Single.zip(
    weatherService.getTemp(city1),
    weatherService.getTemp(city2),
    (t1, t2) -> t1 > t2 ? city1 : city2)

```

But RxJava doesn't really fit with android-priority-jobqueue because of the mentioned reason.

So my questions would be:
1. Do you maybe have a tip on how would you solve this use-case with jobqueue?
2. Have you maybe though about making the lib Rx compatible? Something like instead of having _void onRun()_, having a _Rx.Single\<T\> task()_ method to return an Rx chain that is executed (subscribed to) by the JobManager. Would something like this make sense?

Thank you in advance!
(I would appreciate any relating thoughts you have regardless of the actual questions.)

**Comment by yigit** [comment]
yea job queue does not provide anything within the jobs for parallelization because they are themselves are the unit of parallelization. After 2.0, I'm thinking about some Rx extensions where JobManager can act as a scheduler but have not looked into it yet (and i know very little Rx).

For your use case though, since both of these jobs are non-persistent, you can reference each other to do the work. Definitely uglier than Rx but should work.

For your use case, in v2, I'm introducing a [JobManagerCallback](https://github.com/yigit/android-priority-jobqueue/blob/v2/jobqueue/src/main/java/com/path/android/jobqueue/callback/JobManagerCallback.java) class which can be notified when a job is done. You could implement this feature on top of JobManagerCallback by listening both jobs. 

About v2, although all tests are passing, it is not released yet.

With v1, something like this might work:

    class GetTmpJob extends Job {
       final GetTmpJob companion; // the other job
       float temperature; // the result
       String city;
       AtomicInteger counter;// to sync two jobs
       public GetTmpJob(String city, AtomicInteger counter)...
       public void onRun() {
             temperature = webservice.getTemperature(city);
             dispatchIfDone();
       }
       public void onCancel() {
            dispatchIfDone();
       }
       private void dispatchIfDone() {
            if (counter.decrementAndGet() == 0) {
                 // now both jobs are finished, do whatever you want.
            }
       }
    }

Now you can use this like:

    AtomicInteger lock = new AtomicInteger(2);
    GetTmpJob j1 = new GetTmpJob(city1, lock);
    GetTmpJob j2 = new GetTmpJob(city2, lock);
    j1.setCompanion(j2);
    j2.setCompanion(j1);
    jobManager.addJobInBackground(j1);
    jobManager.addJobInBackground(j2);


Now this is a lot of code but you can easily create a generic Zip job that does this for you for N number of jobs.  Thats basically what Rx provides. If you are starting new, I highly suggest using V2 because I'm breaking some APIs (even might move some packages). I'm hoping to publish the snapshot this weekend. (i was going to do earlier but got side tracked by some CI issues).

**Comment by lemonboston** [comment]
Thanks a lot for the detailed answer!
It's great to hear that v2 is coming! And even more capabilities.. wow. Looking forward to check it out later. 

Thanks also for concrete example of how it could be done in v1 - like it :)

**Comment by AlokBansal8** [comment]
:+1:

**Comment by yigit** [comment]
glad it helped. I've also published 2.0 SNAPSHOT to maven central if you would like to take a look at it.

**Comment by lemonboston** [comment]
Thanks for the info and congrats for the milestone! :)
(I am only doing PoCs btw, and have started working on other parts, so I plan to check back some time later for the real v2 release.)

**Comment by ZakTaccardi** [comment]
You can be Rx friendly with a little hacking in v2. Haven't had the chance to implement this yet, but this should work.

Extend the `Job` class with a class like `BaseRxJob` that has two methods that must be called for a job to complete: `onJobSuccess()` or `onJobFailed(@Nullable Throwable t)`. Make the `onRun()` private in the base class (and create an `onRxRun()` abstract method), and block it from completing until either `onJobSuccess()` or `onJobFailed(t)` are called.

Now you can have all the threads you want!
